### ISSUE TITLE
Commands Only Working for Admin

### ISSUE THREAD

**Issue by Elite911** [kyleshepherd/tarkov-tk#17]
Hello,

Had an issue with the bot not working. So I made a new channel and the bot works now but seems only admins can log teamkills with it. I've checked permissions and everyone has access to the application command in Server settings. Have any idea what else it might be?

Thank you.

**Comment by kyleshepherd** [comment]
I can't replicate this so I'm not sure if it's an issue with the bot itself

**Comment by Elite911** [comment]
Hmm, strange. Any suggestions on what I could try?

**Comment by kyleshepherd** [comment]
The only thing I could think is to remove and re-add the Bot. You won't lose any data doing this

**Comment by Elite911** [comment]
Thanks, Kyle.

That actually fixed the issue. You can close this issue. :)
